name: Testes Automatizados LILI App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r lili_app-documentado/requirements.txt
        pip install pytest streamlit rapidfuzz vosk simpleaudio sounddevice pyttsx3

    - name: Executar testes
      run: |
        pytest lili_app_documentado/tests
